export const topicFavouritesChartConstants = {
  filters: {
    periods: [
      { label: "Tháng 05/2026", type: "month", value: "2026-05" },
      { label: "Năm 2026", type: "year", value: "2026" },
    ],
    rankings: ["top5", "top10", "top20"],
  },
  month: {
    period: "2026-05",
    top5: [
      {
        rank: 1,
        topic: "Điểm chuẩn các trường",
        sessions: 1840,
        sharePercent: 14.8,
      },
      {
        rank: 2,
        topic: "Phương thức xét tuyển",
        sessions: 1715,
        sharePercent: 13.8,
      },
      {
        rank: 3,
        topic: "Tư vấn ngành học",
        sessions: 1620,
        sharePercent: 13.0,
      },
      { rank: 4, topic: "Hồ sơ xét tuyển", sessions: 1495, sharePercent: 12.0 },
      { rank: 5, topic: "Lich nộp hồ sơ", sessions: 1400, sharePercent: 11.2 },
    ],
    top10: [
      {
        rank: 1,
        topic: "Điểm chuẩn các trường",
        sessions: 1840,
        sharePercent: 14.8,
      },
      {
        rank: 2,
        topic: "Phương thức xét tuyển",
        sessions: 1715,
        sharePercent: 13.8,
      },
      {
        rank: 3,
        topic: "Tư vấn ngành học",
        sessions: 1620,
        sharePercent: 13.0,
      },
      { rank: 4, topic: "Hồ sơ xét tuyển", sessions: 1495, sharePercent: 12.0 },
      { rank: 5, topic: "Lich nộp hồ sơ", sessions: 1400, sharePercent: 11.2 },
      {
        rank: 6,
        topic: "Học phí và học bổng",
        sessions: 1280,
        sharePercent: 10.3,
      },
      {
        rank: 7,
        topic: "Tổ hợp môn xét tuyển",
        sessions: 1175,
        sharePercent: 9.4,
      },
      {
        rank: 8,
        topic: "Điều kiện trúng tuyển",
        sessions: 1090,
        sharePercent: 8.8,
      },
      {
        rank: 9,
        topic: "Quy chế tuyển sinh",
        sessions: 980,
        sharePercent: 7.9,
      },
      {
        rank: 10,
        topic: "Chỉ tiêu tuyển sinh",
        sessions: 845,
        sharePercent: 6.8,
      },
    ],
    top20: [
      {
        rank: 1,
        topic: "Điểm chuẩn các trường",
        sessions: 1840,
        sharePercent: 14.8,
      },
      {
        rank: 2,
        topic: "Phương thức xét tuyển",
        sessions: 1715,
        sharePercent: 13.8,
      },
      {
        rank: 3,
        topic: "Tư vấn ngành học",
        sessions: 1620,
        sharePercent: 13.0,
      },
      { rank: 4, topic: "Hồ sơ xét tuyển", sessions: 1495, sharePercent: 12.0 },
      { rank: 5, topic: "Lich nộp hồ sơ", sessions: 1400, sharePercent: 11.2 },
      {
        rank: 6,
        topic: "Học phí và học bổng",
        sessions: 1280,
        sharePercent: 10.3,
      },
      {
        rank: 7,
        topic: "Tổ hợp môn xét tuyển",
        sessions: 1175,
        sharePercent: 9.4,
      },
      {
        rank: 8,
        topic: "Điều kiện trúng tuyển",
        sessions: 1090,
        sharePercent: 8.8,
      },
      {
        rank: 9,
        topic: "Quy chế tuyển sinh",
        sessions: 980,
        sharePercent: 7.9,
      },
      {
        rank: 10,
        topic: "Chỉ tiêu tuyển sinh",
        sessions: 845,
        sharePercent: 6.8,
      },
      { rank: 11, topic: "Học bạ THPT", sessions: 790, sharePercent: 6.3 },
      { rank: 12, topic: "Xét tuyển sớm", sessions: 745, sharePercent: 6.0 },
      {
        rank: 13,
        topic: "Xét điểm thi đánh giá năng lực",
        sessions: 700,
        sharePercent: 5.6,
      },
      {
        rank: 14,
        topic: "Nguyện vọng đăng ký",
        sessions: 670,
        sharePercent: 5.4,
      },
      {
        rank: 15,
        topic: "Hướng dẫn nộp lệ phí",
        sessions: 635,
        sharePercent: 5.1,
      },
      {
        rank: 16,
        topic: "Thông tin tuyển sinh quốc tế",
        sessions: 610,
        sharePercent: 4.9,
      },
      {
        rank: 17,
        topic: "Tuyển sinh cao đẳng",
        sessions: 580,
        sharePercent: 4.7,
      },
      {
        rank: 18,
        topic: "Liên thông đại học",
        sessions: 555,
        sharePercent: 4.5,
      },
      {
        rank: 19,
        topic: "Ưu tiên khu vực đối tượng",
        sessions: 530,
        sharePercent: 4.3,
      },
      {
        rank: 20,
        topic: "Giấy báo trúng tuyển",
        sessions: 505,
        sharePercent: 4.1,
      },
    ],
  },
  year: {
    period: "2026",
    top5: [
      {
        rank: 1,
        topic: "Điểm chuẩn các trường",
        sessions: 19240,
        sharePercent: 16.4,
      },
      {
        rank: 2,
        topic: "Phương thức xét tuyển",
        sessions: 17610,
        sharePercent: 15.0,
      },
      {
        rank: 3,
        topic: "Tư vấn ngành học",
        sessions: 15890,
        sharePercent: 13.5,
      },
      { rank: 4, topic: "Lich nộp hồ sơ", sessions: 14180, sharePercent: 12.1 },
      {
        rank: 5,
        topic: "Hồ sơ xét tuyển",
        sessions: 13620,
        sharePercent: 11.6,
      },
    ],
    top10: [
      {
        rank: 1,
        topic: "Điểm chuẩn các trường",
        sessions: 19240,
        sharePercent: 16.4,
      },
      {
        rank: 2,
        topic: "Phương thức xét tuyển",
        sessions: 17610,
        sharePercent: 15.0,
      },
      {
        rank: 3,
        topic: "Tư vấn ngành học",
        sessions: 15890,
        sharePercent: 13.5,
      },
      { rank: 4, topic: "Lich nộp hồ sơ", sessions: 14180, sharePercent: 12.1 },
      {
        rank: 5,
        topic: "Hồ sơ xét tuyển",
        sessions: 13620,
        sharePercent: 11.6,
      },
      {
        rank: 6,
        topic: "Học phí và học bổng",
        sessions: 12450,
        sharePercent: 10.6,
      },
      {
        rank: 7,
        topic: "Tổ hợp môn xét tuyển",
        sessions: 11520,
        sharePercent: 9.8,
      },
      {
        rank: 8,
        topic: "Điều kiện trúng tuyển",
        sessions: 10710,
        sharePercent: 9.1,
      },
      {
        rank: 9,
        topic: "Quy chế tuyển sinh",
        sessions: 9520,
        sharePercent: 8.1,
      },
      {
        rank: 10,
        topic: "Chỉ tiêu tuyển sinh",
        sessions: 8940,
        sharePercent: 7.6,
      },
    ],
    top20: [
      {
        rank: 1,
        topic: "Điểm chuẩn các trường",
        sessions: 19240,
        sharePercent: 16.4,
      },
      {
        rank: 2,
        topic: "Phương thức xét tuyển",
        sessions: 17610,
        sharePercent: 15.0,
      },
      {
        rank: 3,
        topic: "Tư vấn ngành học",
        sessions: 15890,
        sharePercent: 13.5,
      },
      { rank: 4, topic: "Lich nộp hồ sơ", sessions: 14180, sharePercent: 12.1 },
      {
        rank: 5,
        topic: "Hồ sơ xét tuyển",
        sessions: 13620,
        sharePercent: 11.6,
      },
      {
        rank: 6,
        topic: "Học phí và học bổng",
        sessions: 12450,
        sharePercent: 10.6,
      },
      {
        rank: 7,
        topic: "Tổ hợp môn xét tuyển",
        sessions: 11520,
        sharePercent: 9.8,
      },
      {
        rank: 8,
        topic: "Điều kiện trúng tuyển",
        sessions: 10710,
        sharePercent: 9.1,
      },
      {
        rank: 9,
        topic: "Quy chế tuyển sinh",
        sessions: 9520,
        sharePercent: 8.1,
      },
      {
        rank: 10,
        topic: "Chỉ tiêu tuyển sinh",
        sessions: 8940,
        sharePercent: 7.6,
      },
      { rank: 11, topic: "Học bạ THPT", sessions: 8420, sharePercent: 7.2 },
      { rank: 12, topic: "Xét tuyển sớm", sessions: 8010, sharePercent: 6.8 },
      {
        rank: 13,
        topic: "Xét điểm thi đánh giá năng lực",
        sessions: 7630,
        sharePercent: 6.5,
      },
      {
        rank: 14,
        topic: "Nguyện vọng đăng ký",
        sessions: 7290,
        sharePercent: 6.2,
      },
      {
        rank: 15,
        topic: "Hướng dẫn nộp lệ phí",
        sessions: 6980,
        sharePercent: 5.9,
      },
      {
        rank: 16,
        topic: "Thông tin tuyển sinh quốc tế",
        sessions: 6650,
        sharePercent: 5.7,
      },
      {
        rank: 17,
        topic: "Tuyển sinh cao đẳng",
        sessions: 6320,
        sharePercent: 5.4,
      },
      {
        rank: 18,
        topic: "Liên thông đại học",
        sessions: 6140,
        sharePercent: 5.2,
      },
      {
        rank: 19,
        topic: "Ưu tiên khu vực đối tượng",
        sessions: 5890,
        sharePercent: 5.0,
      },
      {
        rank: 20,
        topic: "Giấy báo trúng tuyển",
        sessions: 5620,
        sharePercent: 4.8,
      },
    ],
  },
};
