export const userTrackingChatbotConstants = {
  pageSizeOptions: [10, 20, 50],
  defaultPageSize: 10,
  records: [
    {
      trackingId: "#45169",
      topic: "Tuyển sinh 2024",
      time: "15/06/2022",
      username: "Nguyễn Minh Anh",
      email: "minh.anh@gmail.com",
      tag: "Process",
    },
    {
      trackingId: "#34304",
      topic: "Tuyển sinh 2023",
      time: "06/09/2022",
      username: "Trần Gia Huy",
      email: "gia.huy@gmail.com",
      tag: "Queued",
    },
    {
      trackingId: "#17188",
      topic: "Tuyển sinh 2022",
      time: "25/09/2022",
      username: "Lê Khánh Linh",
      email: "khanh.linh@gmail.com",
      tag: "Canceled",
    },
    {
      trackingId: "#17189",
      topic: "Tuyển sinh 2022",
      time: "25/09/2022",
      username: "Phạm Đức Long",
      email: "duc.long@gmail.com",
      tag: "Canceled",
    },
    {
      trackingId: "#17190",
      topic: "Tuyển sinh 2022",
      time: "25/09/2022",
      username: "Vũ Thảo My",
      email: "thao.my@gmail.com",
      tag: "Success",
    },
    {
      trackingId: "#17191",
      topic: "Điểm chuẩn các trường",
      time: "03/01/2026",
      username: "Nguyễn An",
      email: "an.nguyen@gmail.com",
      tag: "Success",
    },
    {
      trackingId: "#17192",
      topic: "Phương thức xét tuyển",
      time: "04/01/2026",
      username: "Trần Bình",
      email: "binh.tran@gmail.com",
      tag: "Process",
    },
    {
      trackingId: "#17193",
      topic: "Hồ sơ xét tuyển",
      time: "05/01/2026",
      username: "Lê Chi",
      email: "chi.le@gmail.com",
      tag: "Success",
    },
    {
      trackingId: "#17194",
      topic: "Lịch nộp hồ sơ",
      time: "06/01/2026",
      username: "Phạm Dũng",
      email: "dung.pham@gmail.com",
      tag: "Review",
    },
    {
      trackingId: "#17195",
      topic: "Chỉ tiêu tuyển sinh",
      time: "07/01/2026",
      username: "Võ Em",
      email: "em.vo@gmail.com",
      tag: "Canceled",
    },
    {
      trackingId: "#17196",
      topic: "Học phí và học bổng",
      time: "08/01/2026",
      username: "Hoàng Giang",
      email: "giang.hoang@gmail.com",
      tag: "Success",
    },
    {
      trackingId: "#17197",
      topic: "Tổ hợp môn xét tuyển",
      time: "09/01/2026",
      username: "Bùi Hiếu",
      email: "hieu.bui@gmail.com",
      tag: "Process",
    },
    {
      trackingId: "#17198",
      topic: "Điều kiện trúng tuyển",
      time: "10/01/2026",
      username: "Đỗ Khánh",
      email: "khanh.do@gmail.com",
      tag: "Success",
    },
    {
      trackingId: "#17199",
      topic: "Quy chế tuyển sinh",
      time: "11/01/2026",
      username: "Đặng Lâm",
      email: "lam.dang@gmail.com",
      tag: "Process",
    },
    {
      trackingId: "#17200",
      topic: "Xét tuyển sớm",
      time: "12/01/2026",
      username: "Ngô My",
      email: "my.ngo@gmail.com",
      tag: "Canceled",
    },
    {
      trackingId: "#17201",
      topic: "Xét điểm thi đánh giá năng lực",
      time: "13/01/2026",
      username: "Cao Nam",
      email: "nam.cao@gmail.com",
      tag: "Success",
    },
    {
      trackingId: "#17202",
      topic: "Nguyện vọng đăng ký",
      time: "14/01/2026",
      username: "Phan Oanh",
      email: "oanh.phan@gmail.com",
      tag: "Escalated",
    },
    {
      trackingId: "#17203",
      topic: "Hướng dẫn nộp lệ phí",
      time: "15/01/2026",
      username: "Vũ Phúc",
      email: "phuc.vu@gmail.com",
      tag: "Success",
    },
    {
      trackingId: "#17204",
      topic: "Tuyển sinh cao đẳng",
      time: "16/01/2026",
      username: "Mạc Quỳnh",
      email: "quynh.mac@gmail.com",
      tag: "Process",
    },
    {
      trackingId: "#17205",
      topic: "Liên thông đại học",
      time: "17/01/2026",
      username: "Lý Sơn",
      email: "son.ly@gmail.com",
      tag: "Canceled",
    },
    {
      trackingId: "#17206",
      topic: "Ưu tiên khu vực đối tượng",
      time: "18/01/2026",
      username: "Trương Thái",
      email: "thai.truong@gmail.com",
      tag: "Success",
    },
    {
      trackingId: "#17207",
      topic: "Giấy báo trúng tuyển",
      time: "19/01/2026",
      username: "Ninh Uyên",
      email: "uyen.ninh@gmail.com",
      tag: "Process",
    },
    {
      trackingId: "#17208",
      topic: "Tuyển sinh quốc tế",
      time: "20/01/2026",
      username: "Kiều Vân",
      email: "van.kieu@gmail.com",
      tag: "Success",
    },
    {
      trackingId: "#17209",
      topic: "Tư vấn ngành học",
      time: "21/01/2026",
      username: "Âu Xuân",
      email: "xuan.au@gmail.com",
      tag: "Process",
    },
    {
      trackingId: "#17210",
      topic: "Đối tượng ưu tiên",
      time: "22/01/2026",
      username: "Lưu Yến",
      email: "yen.luu@gmail.com",
      tag: "Canceled",
    },
    {
      trackingId: "#17211",
      topic: "Ngành hot 2026",
      time: "23/01/2026",
      username: "Mai Anh",
      email: "anh.mai@gmail.com",
      tag: "Success",
    },
    {
      trackingId: "#17212",
      topic: "Tuyển sinh học bạ",
      time: "24/01/2026",
      username: "Quốc Bảo",
      email: "bao.quoc@gmail.com",
      tag: "Process",
    },
    {
      trackingId: "#17213",
      topic: "Điểm sàn xét tuyển",
      time: "25/01/2026",
      username: "Cẩm Châu",
      email: "chau.cam@gmail.com",
      tag: "Success",
    },
    {
      trackingId: "#17214",
      topic: "Nộp minh chứng ưu tiên",
      time: "26/01/2026",
      username: "Đức Đạt",
      email: "dat.duc@gmail.com",
      tag: "Queued",
    },
    {
      trackingId: "#17215",
      topic: "Xác nhận nhập học",
      time: "27/01/2026",
      username: "Gia Hân",
      email: "han.gia@gmail.com",
      tag: "Success",
    },
    {
      trackingId: "#17216",
      topic: "Rút hồ sơ xét tuyển",
      time: "28/01/2026",
      username: "Hải Kiệt",
      email: "kiet.hai@gmail.com",
      tag: "Canceled",
    },
    {
      trackingId: "#17217",
      topic: "Cập nhật nguyện vọng",
      time: "29/01/2026",
      username: "Hồng Linh",
      email: "linh.hong@gmail.com",
      tag: "Process",
    },
    {
      trackingId: "#17218",
      topic: "Tra cứu kết quả trúng tuyển",
      time: "30/01/2026",
      username: "Khánh Minh",
      email: "minh.khanh@gmail.com",
      tag: "Success",
    },
    {
      trackingId: "#17219",
      topic: "Tuyển sinh ngành y",
      time: "31/01/2026",
      username: "Long Nam",
      email: "nam.long@gmail.com",
      tag: "Process",
    },
    {
      trackingId: "#17220",
      topic: "Tuyển sinh ngành công nghệ",
      time: "01/02/2026",
      username: "Mỹ Ngân",
      email: "ngan.my@gmail.com",
      tag: "Success",
    },
    {
      trackingId: "#17221",
      topic: "Tuyển sinh ngành kinh tế",
      time: "02/02/2026",
      username: "Phúc Quang",
      email: "quang.phuc@gmail.com",
      tag: "Process",
    },
    {
      trackingId: "#17222",
      topic: "Tuyển sinh ngành sư phạm",
      time: "03/02/2026",
      username: "Quyền Trang",
      email: "trang.quyen@gmail.com",
      tag: "Canceled",
    },
    {
      trackingId: "#17223",
      topic: "Đối chiếu điểm học bạ",
      time: "04/02/2026",
      username: "Sơn Tùng",
      email: "tung.son@gmail.com",
      tag: "Success",
    },
    {
      trackingId: "#17224",
      topic: "Đăng ký nguyện vọng online",
      time: "05/02/2026",
      username: "Thị Uyên",
      email: "uyen.thi@gmail.com",
      tag: "Process",
    },
    {
      trackingId: "#17225",
      topic: "Nhập học đợt 1",
      time: "06/02/2026",
      username: "Vân Vy",
      email: "vy.van@gmail.com",
      tag: "Success",
    },
    {
      trackingId: "#17226",
      topic: "Nhập học đợt 2",
      time: "07/02/2026",
      username: "Xuân Yến",
      email: "yen.xuan@gmail.com",
      tag: "Review",
    },
    {
      trackingId: "#17227",
      topic: "Phúc khảo kết quả",
      time: "08/02/2026",
      username: "Yến An",
      email: "an.yen@gmail.com",
      tag: "Canceled",
    },
    {
      trackingId: "#17228",
      topic: "Bổ sung hồ sơ",
      time: "09/02/2026",
      username: "Zan Bình",
      email: "binh.zan@gmail.com",
      tag: "Process",
    },
    {
      trackingId: "#17229",
      topic: "Tuyển sinh hệ chất lượng cao",
      time: "10/02/2026",
      username: "An Chi",
      email: "chi.an@gmail.com",
      tag: "Success",
    },
    {
      trackingId: "#17230",
      topic: "Tuyển sinh chương trình quốc tế",
      time: "11/02/2026",
      username: "Bình Dương",
      email: "duong.binh@gmail.com",
      tag: "Process",
    },
    {
      trackingId: "#17231",
      topic: "Thông báo kết quả sơ tuyển",
      time: "12/02/2026",
      username: "Cường Giáp",
      email: "giap.cuong@gmail.com",
      tag: "Success",
    },
    {
      trackingId: "#17232",
      topic: "Hướng dẫn đăng ký ngành",
      time: "13/02/2026",
      username: "Diệp Hạnh",
      email: "hanh.diep@gmail.com",
      tag: "Process",
    },
    {
      trackingId: "#17233",
      topic: "Mốc thời gian quan trọng",
      time: "14/02/2026",
      username: "Giang Huy",
      email: "huy.giang@gmail.com",
      tag: "Success",
    },
    {
      trackingId: "#17234",
      topic: "Khu vực tuyển sinh",
      time: "15/02/2026",
      username: "Hải Khoa",
      email: "khoa.hai@gmail.com",
      tag: "Process",
    },
    {
      trackingId: "#17235",
      topic: "Hướng dẫn nhập học online",
      time: "16/02/2026",
      username: "Lâm Mai",
      email: "mai.lam@gmail.com",
      tag: "Success",
    },
    {
      trackingId: "#17236",
      topic: "Thông tin ký túc xá",
      time: "17/02/2026",
      username: "Minh Nhi",
      email: "nhi.minh@gmail.com",
      tag: "Canceled",
    },
    {
      trackingId: "#17237",
      topic: "Lịch khai giảng",
      time: "18/02/2026",
      username: "Oanh Phú",
      email: "phu.oanh@gmail.com",
      tag: "Success",
    },
    {
      trackingId: "#17238",
      topic: "Tuyển sinh bổ sung",
      time: "19/02/2026",
      username: "Quang Sơn",
      email: "son.quang@gmail.com",
      tag: "Process",
    },
  ],
};
